# -*- coding: utf-8 -*-
"""Tempo Real .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_fcQPL4WkWxYX7FvJQxz9oKa5-d0Octe
"""

!pip install folium
!pip install folium.plugins

import folium
from folium.plugins import TimestampedGeoJson
-25.950817702531975, 32.59119218595313

linhas = [
    {"coord": [[32.58853772337319, -25.953344399451808], [32.589372124888584, -25.951997610988077]],
     "datas": ["2023-04-11T09:01:00", "2023-04-11T09:05:00"],
     "estilo_icone": {"radius": 0}},

    {"coord": [[32.589372124888584, -25.951997610988077], [32.590092623063065, -25.952378194720957]],
     "datas": ["2023-04-11T09:05:00", "2023-04-11T09:10:00"],
     "estilo_icone": {"radius": 0}},

    {"coord": [[32.590092623063065, -25.952378194720957], [32.59119218595313, -25.950817702531975]],
     "datas": ["2023-04-11T09:10:00", "2023-04-11T09:15:00"],
     "estilo_icone": {"radius": 0}},

    {"coord": [[32.59119218595313, -25.950817702531975], [32.59188450277029, -25.949868439599847]],
     "datas": ["2023-04-11T09:15:00", "2023-04-11T09:20:00"],
     "estilo_icone": {"radius": 0}},

    {"coord": [[32.59188450277029, -25.949868439599847], [32.59188137036536, -25.949279724215465]],
     "datas": ["2023-04-11T09:20:00", "2023-04-11T09:25:00"],
     "estilo_icone": {"radius": 0},
     },

    {"coord": [[32.59188137036536, -25.949279724215465], [32.5924953708069, -25.948772693963807]],
     "datas": ["2023-04-11T09:25:00", "2023-04-11T09:35:00"],
     "estilo_icone": {"radius": 0}},

    {"coord": [[32.5924953708069, -25.948772693963807], [32.59826617286751, -25.94873197355251]],
     "datas": ["2023-04-11T09:35:00", "2023-04-11T09:40:00"],
     "estilo_icone": {"radius": 0}},

    {"coord": [[32.59826617286751, -25.94873197355251], [32.59948891065825, -25.949656208232284]],
     "datas": ["2023-04-11T09:40:00", "2023-04-11T09:45:00"],
     "estilo_icone": {"radius": 10},
     "popup": """<figure>
                 <figcaption> Departamento de Matemática e Informática, UEM</figcaption>
                 </figure>"""
    },

]


features = []

for dado in linhas:
    features.append({"type": "Feature",
                    "geometry": {"type": "LineString",
                                "coordinates": dado["coord"]},
                    "properties": {"times": dado["datas"],
                                  "style": {"color": "#16BAB6",
                                           "weight": 3},
                                  "icon": "circle",
                                  "iconstyle": dado["estilo_icone"],
                                  "popup": dado["popup"] if "popup" in dado else ""}})

mapa = folium.Map([-25.952378194720957, 32.58853772337319],
                 tiles = "cartodbpositron",
                 zoom_start = 16)

TimestampedGeoJson(data = {"type": "FeatureCollection",
                          "features": features},
                  period = "PT1M",
                  loop = False).add_to(mapa)

mapa

